name: CI/CD Pipeline for ML Model

on:
  push:
    branches:
      - master

jobs:
  train-and-evaluate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.2'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: pytest
      - name: Train model
        run: python app/ml/train.py
      - name: Deploy model
        run: |
          # Add deployment steps (e.g., to cloud service)
          echo "Deploying model..."